### PR TITLE
Bump headers of docs with h1 headers

### PR DESCRIPTION
**Pull request by thejcannon**
Fixes https://github.com/pantsbuild/pantsbuild.org/issues/112 by bumping all headers down one level if any of them are `h1`.

Replacement done via:

```python
def replace_headers(text: str):
    lines = text.splitlines(True)
    in_codeblock = False
    has_h1_header = False
    for index, line in enumerate(lines):
        if line.startswith("```"):
            in_codeblock = not in_codeblock
            continue

        if line.startswith("# ") and not in_codeblock:
            has_h1_header = True

        if line.startswith("#") and not in_codeblock and has_h1_header:
            lines[index] = "#" + line
    return "".join(lines)
```

### CODE REVIEW

**Comment by thejcannon** [comment]
(Will need to port this to pantsbuild/pants)

**Comment by huonw** [comment]
Oh, it looks like we've duplicated effort: #117. Oops.

The diffs have different numbers, which makes be a bit suspicious...

**Comment by huonw** [comment]
Potential sources of differences:

- the script won't handle the `1. # ...` nesting on `initial-configuration.mdx`
- #117 only changes files that had more than one `h1`, whereas it looks like this catches a few that have a single inappropriate inline `h1` too
- #117 changes the blog too

**Comment by thejcannon** [comment]
- yeah, I think that file is special and should be handled specially (in a dedicated PR)
- Yes. And I think that's important because IIRC the "title" already becomes the one true h1 (sorry can't validate, I'm on mobile)
- I think the blog _can_ have a single h1, since we Docusaurus doesn't provide one. So we can handle it in another PR with another script

**Review by huonw — APPROVED** [review]

**Comment by huonw** [comment]
- I was assuming we could at least bump the h1s to h2s, not fix the weird list syntax.
- docusaurus seems to skip adding the page title if it detects a manual h1, so not strictly necessary for "correctness", but yes, definitely an improvement.
- I don't know what you mean, the blog needs the fixes too because some posts have multiple h1s. In any case, my duplicate work already fixes the blog, no need for doing more work/scripts, we can just extract from there.

**Pull request merged**
