### PR TITLE
blog post for in-workspace execution

### PR DESCRIPTION
**Pull request by tdyas**
Add blog post for the in-workspace execution support in Pants v2.23.0.

### CODE REVIEW

**Comment by tdyas** [comment]
https://github.com/pantsbuild/example-workspace-execution/pull/2 which adds Docker support to the example repository needs to land first.

**Review by benjyw — APPROVED** [review]
Looks great!! Thanks.

**Comment by benjyw** [comment]
What about a splash image? I think all posts have one

**Comment by tdyas** [comment]
> What about a splash image? I think all posts have one

I don't recall having done a splash image for the user survey blog post.

I'm not really a fan of having to choose stock art with some tangential relation to the "workspace" or "sandbox" theme of the blog post, mainly because my aesthetic sense is lacking.

**Comment by tdyas** [comment]
I added a splash image from Unsplash of a generic office "workspace"

**Comment by tdyas** [comment]
Made more edits.

**Comment by benjyw** [comment]
> I added a splash image from Unsplash of a generic office "workspace"

Cool. Can you post a screenshot of the render?

**Comment by tdyas** [comment]
Rendered:

Screenshot 2024-12-03 at 15-22-43 In-Workspace Execution in Pants v2 23 x Pantsbuild

**Pull request merged**
