### PR TITLE
Manually set `provider` for `environments-preview` in reference docs

### PR DESCRIPTION
**Pull request by thejcannon**
This change massages the data such that the `environments-preview` subsystem is always `pants.core`. And regenerates relevant docs.

### CODE REVIEW

**Comment by kaos** [comment]
before special casing this, I would've thought you could solve this by returning
https://github.com/pantsbuild/pants/blob/afc7d499d23b45b82760c7352d9d026dad9cb418/src/python/pants/core/util_rules/environments.py#L1092
from here:
https://github.com/pantsbuild/pants/blob/afc7d499d23b45b82760c7352d9d026dad9cb418/src/python/pants/core/register.py#L88

have you tried that?

**Comment by thejcannon** [comment]
Even if we did that (which we probably should), it wouldn't solve the issue of branches that don't have that setting applied. So no matter what we still need to work around it here :man_shrugging:

**Review by benjyw — APPROVED** [review]

**Comment by kaos** [comment]
> [..] of branches that don't have that setting applied

What do you mean by this?

**Review by kaos — DISMISSED** [review]
I'll have a look at my idea of fixing this before landing this, will introduce me to the new docs as well which is a good thing :)

**Comment by kaos** [comment]
From what I can tell, my fix in pantsbuild/pants#20444 addresses the same thing as this PR, but without the kludge of special-casing in the generate script.

How do we go about getting the `help-all.json` updated?
I tried a simple `pants help-all > ../pantsbuild.org/docs/reference/help-all.json` but that gave a larger diff than anticipated.

Oh, or that may be automated?

**Comment by thejcannon** [comment]
So the script handles all versions of pants back to 2.0. This bug started in the help all of 2.15.x. That means that even if we fix it, the JSON we're running on won't fixed fire those older versions. Hence needing to special case it in the script anyways.

---

The help-all JSON is updated as part of docs syncing in the `sync_docs.yaml` action. It gets triggered after a release is published.

**Comment by kaos** [comment]
Ah, right. OK.

**Review by kaos — APPROVED** [review]

**Pull request merged**
