### PR TITLE
Update docs site for version 2.21.0.dev0

### PR DESCRIPTION
**Pull request by WorkerPants**
Docs from https://github.com/pantsbuild/pants/releases/tag/release_2.21.0.dev0

### CODE REVIEW

**Comment by huonw** [comment]
@thejcannon I'm a bit unclear about how the "new version" creation is meant to happen: it seems both #161 (2.20.0rc0) and this PR (2.21.0.dev0) update `docs/` directly, with neither creating a new `versioned_docs/2.20/` directory.

Do you happen to remember how the process is meant to happen?

**Comment by huonw** [comment]
Ah, it's intended to happen in the `a0` release: https://github.com/pantsbuild/pantsbuild.org/blob/f277f2632030cd209be3b6c3f9ea5cc4ca4e2aa4/.github/workflows/sync_docs.yml#L78

That is, https://github.com/pantsbuild/pantsbuild.org/pull/153 should've done it but a minor typo prevented it. #163 fixes.

**Comment by thejcannon** [comment]
Yeah you beat me to it. 👍

**Comment by huonw** [comment]
Closing and then rerunning the sync after #164 merged.

**Pull request closed without merging**
