### PR TITLE
Sponsors page.

### PR DESCRIPTION
**Pull request by benjyw**
Also remove the old jobs page, since we now want
sponsorship to be the route to job postings, and
in any case that page was hopelessly out of date.

The logos and blurbs came from the sponsors.
Any sponsors seeing this who would like to make
a change, feel free to submit a PR in this repo, 
or message me.

### CODE REVIEW

**Comment by benjyw** [comment]
Renders like so:

sponsors_page_rendered

**Comment by benjyw** [comment]
I tried to do something with color for the platinum vs silver, but it didn't look very appealing.

**Review by cburroughs — APPROVED** [review]
I took a copy editing pass and I think everything looks good.

**Review by tgolsson — APPROVED** [review]
All looks good to me!

**Pull request merged**
